import type { Metadata } from "next";
import { Dancing_Script, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const dancingscript_init = Dancing_Script({
  subsets: ["latin"],
  weight: ['400','500','600','700'],
  variable: '--font-dancingscript',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dancingscript_init.variable}>{children}</body>
    </html>
  );
}
